name       : geeqie
version    : 2.0.1
release    : 12
source     :
    - https://github.com/BestImageViewer/geeqie/archive/refs/tags/v2.0.1.tar.gz : 6d87004a21b91afb7ea9eac3624fc37f5ccf1818fd40f567f8c7d1b5cbc2a6c7
homepage   : https://www.geeqie.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Geeqie is a lightweight image viewer
description: |
    Geeqie is a lightweight image viewer for Linux, BSDs and compatibles. It can be used as a simple, fast, database-free image viewer, but equally it can be used to manage large collections of images.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(ddjvuapi)
    - pkgconfig(exiv2)
    - pkgconfig(gspell-1)
    - pkgconfig(libarchive)
    - pkgconfig(libffmpegthumbnailer)
    - pkgconfig(libheif)
    - pkgconfig(libjpeg)
    - pkgconfig(libopenjp2)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(lua)
    - pkgconfig(poppler-glib)
    - vim     # for /usr/bin/xxd
rundeps    :
    - gphoto2
    - perl-image-exiftool
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
