name       : geeqie
version    : '1.6'
release    : 2
source     :
    - https://github.com/BestImageViewer/geeqie/releases/download/v1.6/geeqie-1.6.tar.xz : 48f8a4474454d182353100e43878754b76227f3b8f30cfc258afc9d90a4e1920
homepage   : http://geeqie.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Geeqie is a lightweight image viewer
description: |
    Geeqie is a lightweight image viewer for Linux, BSDs and compatibles. It can be used as a simple, fast, database-free image viewer, but equally it can be used to manage large collections of images.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(ddjvuapi)
    - pkgconfig(exiv2)
    - pkgconfig(lcms2)
    - pkgconfig(libffmpegthumbnailer)
    - pkgconfig(libheif)
    - pkgconfig(libjpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(lirc)
    - pkgconfig(lua)
    - pkgconfig(poppler-glib)
rundeps    :
    - gphoto2
    - perl-image-exiftool
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-Help-and-Changelog-references-to-docs.patch
    sed -i 's/\-Werror//' configure.ac
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
