name       : geeqie
version    : 1.5.1
release    : 1
source     :
    - http://geeqie.org/geeqie-1.5.1.tar.xz : 4854d5d323c31f8f4068fd73ab2c454ff91e826c4ca4d37b22c246ad14dea10a
homepage   : http://geeqie.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Geeqie is a lightweight image viewer
description: |
    Geeqie is a lightweight image viewer for Linux, BSDs and compatibles.It can be used as a simple, fast, database-free image viewer, but equally it can be used to manage large collections of images.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(exiv2)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(lcms2)
    - pkgconfig(libffmpegthumbnailer)
    - pkgconfig(libjpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(lirc)
    - pkgconfig(lua)
    - pkgconfig(poppler-glib)
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-Help-and-Changelog-references-to-docs.patch
    sed -i 's/\-Werror//' configure.ac
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
